INSERT INTO countries(id, name, capital, currency, population) values (	1	,'Afghanistan','Kabul','Afghani',	1000000	);
INSERT INTO countries(id, name, capital, currency, population) values (	2	,'Albania','Tirana','Lek',	1300000	);
INSERT INTO countries(id, name, capital, currency, population) values (	3	,'Algeria','Algiers','Dinar',	4700000	);
INSERT INTO countries(id, name, capital, currency, population) values (	4	,'American Samoa','Pago Pago','Dollar',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	5	,'Andorra','Andorra la Vella','Euro',	67100	);
INSERT INTO countries(id, name, capital, currency, population) values (	6	,'Angola','Luanda','Kwanza',	606700	);
INSERT INTO countries(id, name, capital, currency, population) values (	7	,'Anguilla','The Valley','Dollar',	3700	);
INSERT INTO countries(id, name, capital, currency, population) values (	8	,'Antarctica','-','-',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	9	,'Antigua and Barbuda','St. John''s','Dollar',	65000	);
INSERT INTO countries(id, name, capital, currency, population) values (	10	,'Argentina','Buenos Aires','Peso',	13694000	);
INSERT INTO countries(id, name, capital, currency, population) values (	11	,'Armenia','Yerevan','Dram',	208200	);
INSERT INTO countries(id, name, capital, currency, population) values (	12	,'Aruba','Oranjestad','Guilder',	24000	);
INSERT INTO countries(id, name, capital, currency, population) values (	13	,'Australia','Canberra','Dollar',	15810000	);
INSERT INTO countries(id, name, capital, currency, population) values (	14	,'Austria','Vienna','Euro',	6143000	);
INSERT INTO countries(id, name, capital, currency, population) values (	15	,'Azerbaijan','Baku','Manat',	2420000	);
INSERT INTO countries(id, name, capital, currency, population) values (	16	,'Bahamas','Nassau','Dollar',	115800	);
INSERT INTO countries(id, name, capital, currency, population) values (	17	,'Bahrain','Manama','Dinar',	419500	);
INSERT INTO countries(id, name, capital, currency, population) values (	18	,'Bangladesh','Dhaka','Taka',	617300	);
INSERT INTO countries(id, name, capital, currency, population) values (	19	,'Barbados','Bridgetown','Dollar',	188000	);
INSERT INTO countries(id, name, capital, currency, population) values (	20	,'Belarus','Minsk','Ruble',	2643000	);
INSERT INTO countries(id, name, capital, currency, population) values (	21	,'Belgium','Brussels','Euro',	8113000	);
INSERT INTO countries(id, name, capital, currency, population) values (	22	,'Belize','Belmopan','Dollar',	36000	);
INSERT INTO countries(id, name, capital, currency, population) values (	23	,'Benin','Porto-Novo','Franc',	200100	);
INSERT INTO countries(id, name, capital, currency, population) values (	24	,'Bermuda','Hamilton','Dollar',	54000	);
INSERT INTO countries(id, name, capital, currency, population) values (	25	,'Bhutan','Thimphu','Ngultrum',	50000	);
INSERT INTO countries(id, name, capital, currency, population) values (	26	,'Bolivia','Sucre','Boliviano',	1103000	);
INSERT INTO countries(id, name, capital, currency, population) values (	27	,'Bosnia and Herzegovina','Sarajevo','Marka',	1422000	);
INSERT INTO countries(id, name, capital, currency, population) values (	28	,'Botswana','Gaborone','Pula',	120000	);
INSERT INTO countries(id, name, capital, currency, population) values (	29	,'Brazil','Brasilia','Real',	75982000	);
INSERT INTO countries(id, name, capital, currency, population) values (	30	,'British Indian Ocean Territory','Diego Garcia','Dollar',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	31	,'British Virgin Islands','Road Town','Dollar',	4000	);
INSERT INTO countries(id, name, capital, currency, population) values (	32	,'Brunei','Bandar Seri Begawan','Dollar',	314900	);
INSERT INTO countries(id, name, capital, currency, population) values (	33	,'Bulgaria','Sofia','Lev',	3395000	);
INSERT INTO countries(id, name, capital, currency, population) values (	34	,'Burkina Faso','Ouagadougou','Franc',	178100	);
INSERT INTO countries(id, name, capital, currency, population) values (	35	,'Burundi','Bujumbura','Franc',	157800	);
INSERT INTO countries(id, name, capital, currency, population) values (	36	,'Cambodia','Phnom Penh','Riels',	78500	);
INSERT INTO countries(id, name, capital, currency, population) values (	37	,'Cameroon','Yaounde','Franc',	749600	);
INSERT INTO countries(id, name, capital, currency, population) values (	38	,'Canada','Ottawa','Dollar',	26960000	);
INSERT INTO countries(id, name, capital, currency, population) values (	39	,'Cape Verde','Praia','Escudo',	150000	);
INSERT INTO countries(id, name, capital, currency, population) values (	40	,'Cayman Islands','George Town','Dollar',	23000	);
INSERT INTO countries(id, name, capital, currency, population) values (	41	,'Central African Republic','Bangui','Franc',	22600	);
INSERT INTO countries(id, name, capital, currency, population) values (	42	,'Chad','N''Djamena','Franc',	168100	);
INSERT INTO countries(id, name, capital, currency, population) values (	43	,'Chile','Santiago','Peso',	7009000	);
INSERT INTO countries(id, name, capital, currency, population) values (	44	,'China','Beijing','Yuan Renminbi',	389000000	);
INSERT INTO countries(id, name, capital, currency, population) values (	45	,'Christmas Island','Flying Fish Cove','Dollar',	464	);
INSERT INTO countries(id, name, capital, currency, population) values (	46	,'Cocos Islands','West Island','Dollar',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	47	,'Colombia','Bogota','Peso',	22538000	);
INSERT INTO countries(id, name, capital, currency, population) values (	48	,'Comoros','Moroni','Franc',	24300	);
INSERT INTO countries(id, name, capital, currency, population) values (	49	,'Cook Islands','Avarua','Dollar',	6000	);
INSERT INTO countries(id, name, capital, currency, population) values (	50	,'Costa Rica','San Jose','Colon',	1485000	);
INSERT INTO countries(id, name, capital, currency, population) values (	51	,'Croatia','Zagreb','Kuna',	2234000	);
INSERT INTO countries(id, name, capital, currency, population) values (	52	,'Cuba','Havana','Peso',	1606000	);
INSERT INTO countries(id, name, capital, currency, population) values (	53	,'Curacao','Willemstad','Guilder',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	54	,'Cyprus','Nicosia','Euro',	433900	);
INSERT INTO countries(id, name, capital, currency, population) values (	55	,'Czech Republic','Prague','Koruna',	6681000	);
INSERT INTO countries(id, name, capital, currency, population) values (	56	,'Democratic Republic of the Congo','Kinshasa','Franc',	290000	);
INSERT INTO countries(id, name, capital, currency, population) values (	57	,'Denmark','Copenhagen','Krone',	4750000	);
INSERT INTO countries(id, name, capital, currency, population) values (	58	,'Djibouti','Djibouti','Franc',	25900	);
INSERT INTO countries(id, name, capital, currency, population) values (	59	,'Dominica','Roseau','Dollar',	28000	);
INSERT INTO countries(id, name, capital, currency, population) values (	60	,'Dominican Republic','Santo Domingo','Peso',	2701000	);
INSERT INTO countries(id, name, capital, currency, population) values (	61	,'East Timor','Dili','Dollar',	2100	);
INSERT INTO countries(id, name, capital, currency, population) values (	62	,'Ecuador','Quito','Dollar',	3352000	);
INSERT INTO countries(id, name, capital, currency, population) values (	63	,'Egypt','Cairo','Pound',	20136000	);
INSERT INTO countries(id, name, capital, currency, population) values (	64	,'El Salvador','San Salvador','Dollar',	746000	);
INSERT INTO countries(id, name, capital, currency, population) values (	65	,'Equatorial Guinea','Malabo','Franc',	14400	);
INSERT INTO countries(id, name, capital, currency, population) values (	66	,'Eritrea','Asmara','Nakfa',	200000	);
INSERT INTO countries(id, name, capital, currency, population) values (	67	,'Estonia','Tallinn','Euro',	971700	);
INSERT INTO countries(id, name, capital, currency, population) values (	68	,'Ethiopia','Addis Ababa','Birr',	447300	);
INSERT INTO countries(id, name, capital, currency, population) values (	69	,'Falkland Islands','Stanley','Pound',	2900	);
INSERT INTO countries(id, name, capital, currency, population) values (	70	,'Faroe Islands','Torshavn','Krone',	37500	);
INSERT INTO countries(id, name, capital, currency, population) values (	71	,'Fiji','Suva','Dollar',	114200	);
INSERT INTO countries(id, name, capital, currency, population) values (	72	,'Finland','Helsinki','Euro',	4393000	);
INSERT INTO countries(id, name, capital, currency, population) values (	73	,'France','Paris','Euro',	45262000	);
INSERT INTO countries(id, name, capital, currency, population) values (	74	,'French Polynesia','Papeete','Franc',	120000	);
INSERT INTO countries(id, name, capital, currency, population) values (	75	,'Gabon','Libreville','Franc',	98800	);
INSERT INTO countries(id, name, capital, currency, population) values (	76	,'Gambia','Banjul','Dalasi',	130100	);
INSERT INTO countries(id, name, capital, currency, population) values (	77	,'Georgia','Tbilisi','Lari',	1300000	);
INSERT INTO countries(id, name, capital, currency, population) values (	78	,'Germany','Berlin','Euro',	65125000	);
INSERT INTO countries(id, name, capital, currency, population) values (	79	,'Ghana','Accra','Cedi',	1297000	);
INSERT INTO countries(id, name, capital, currency, population) values (	80	,'Gibraltar','Gibraltar','Pound',	20200	);
INSERT INTO countries(id, name, capital, currency, population) values (	81	,'Greece','Athens','Euro',	4971000	);
INSERT INTO countries(id, name, capital, currency, population) values (	82	,'Greenland','Nuuk','Krone',	36000	);
INSERT INTO countries(id, name, capital, currency, population) values (	83	,'Grenada','St. George''s','Dollar',	25000	);
INSERT INTO countries(id, name, capital, currency, population) values (	84	,'Guam','Hagatna','Dollar',	90000	);
INSERT INTO countries(id, name, capital, currency, population) values (	85	,'Guatemala','Guatemala City','Quetzal',	2279000	);
INSERT INTO countries(id, name, capital, currency, population) values (	86	,'Guernsey','St Peter Port','Pound',	48300	);
INSERT INTO countries(id, name, capital, currency, population) values (	87	,'Guinea','Conakry','Franc',	95000	);
INSERT INTO countries(id, name, capital, currency, population) values (	88	,'Guinea-Bissau','Bissau','Franc',	37100	);
INSERT INTO countries(id, name, capital, currency, population) values (	89	,'Guyana','Georgetown','Dollar',	189600	);
INSERT INTO countries(id, name, capital, currency, population) values (	90	,'Haiti','Port-au-Prince','Gourde',	1000000	);
INSERT INTO countries(id, name, capital, currency, population) values (	91	,'Honduras','Tegucigalpa','Lempira',	731700	);
INSERT INTO countries(id, name, capital, currency, population) values (	92	,'Hong Kong','Hong Kong','Dollar',	4873000	);
INSERT INTO countries(id, name, capital, currency, population) values (	93	,'Hungary','Budapest','Forint',	6176000	);
INSERT INTO countries(id, name, capital, currency, population) values (	94	,'Iceland','Reykjavik','Krona',	301600	);
INSERT INTO countries(id, name, capital, currency, population) values (	95	,'India','New Delhi','Rupee',	61338000	);
INSERT INTO countries(id, name, capital, currency, population) values (	96	,'Indonesia','Jakarta','Rupiah',	20000000	);
INSERT INTO countries(id, name, capital, currency, population) values (	97	,'Iran','Tehran','Rial',	8214000	);
INSERT INTO countries(id, name, capital, currency, population) values (	98	,'Iraq','Baghdad','Dinar',	325900	);
INSERT INTO countries(id, name, capital, currency, population) values (	99	,'Ireland','Dublin','Euro',	3042000	);
INSERT INTO countries(id, name, capital, currency, population) values (	100	,'Isle of Man','Douglas, Isle of Man','Pound',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	101	,'Israel','Jerusalem','Shekel',	4525000	);
INSERT INTO countries(id, name, capital, currency, population) values (	102	,'Italy','Rome','Euro',	29235000	);
INSERT INTO countries(id, name, capital, currency, population) values (	103	,'Ivory Coast','Yamoussoukro','Franc',	967300	);
INSERT INTO countries(id, name, capital, currency, population) values (	104	,'Jamaica','Kingston','Dollar',	1581000	);
INSERT INTO countries(id, name, capital, currency, population) values (	105	,'Japan','Tokyo','Yen',	99182000	);
INSERT INTO countries(id, name, capital, currency, population) values (	106	,'Jersey','Saint Helier','Pound',	29500	);
INSERT INTO countries(id, name, capital, currency, population) values (	107	,'Jordan','Amman','Dinar',	1642000	);
INSERT INTO countries(id, name, capital, currency, population) values (	108	,'Kazakhstan','Astana','Tenge',	5299000	);
INSERT INTO countries(id, name, capital, currency, population) values (	109	,'Kenya','Nairobi','Shilling',	3996000	);
INSERT INTO countries(id, name, capital, currency, population) values (	110	,'Kiribati','Tarawa','Dollar',	7800	);
INSERT INTO countries(id, name, capital, currency, population) values (	111	,'Kosovo','Pristina','Euro',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	112	,'Kuwait','Kuwait City','Dinar',	1100000	);
INSERT INTO countries(id, name, capital, currency, population) values (	113	,'Kyrgyzstan','Bishkek','Som',	2195000	);
INSERT INTO countries(id, name, capital, currency, population) values (	114	,'Laos','Vientiane','Kip',	300000	);
INSERT INTO countries(id, name, capital, currency, population) values (	115	,'Latvia','Riga','Euro',	1504000	);
INSERT INTO countries(id, name, capital, currency, population) values (	116	,'Lebanon','Beirut','Pound',	1000000	);
INSERT INTO countries(id, name, capital, currency, population) values (	117	,'Lesotho','Maseru','Loti',	76800	);
INSERT INTO countries(id, name, capital, currency, population) values (	118	,'Liberia','Monrovia','Dollar',	20000	);
INSERT INTO countries(id, name, capital, currency, population) values (	119	,'Libya','Tripolis','Dinar',	353900	);
INSERT INTO countries(id, name, capital, currency, population) values (	120	,'Liechtenstein','Vaduz','Franc',	23000	);
INSERT INTO countries(id, name, capital, currency, population) values (	121	,'Lithuania','Vilnius','Euro',	1964000	);
INSERT INTO countries(id, name, capital, currency, population) values (	122	,'Luxembourg','Luxembourg','Euro',	424500	);
INSERT INTO countries(id, name, capital, currency, population) values (	123	,'Macau','Macao','Pataca',	270200	);
INSERT INTO countries(id, name, capital, currency, population) values (	124	,'Macedonia','Skopje','Denar',	1057000	);
INSERT INTO countries(id, name, capital, currency, population) values (	125	,'Madagascar','Antananarivo','Ariary',	319900	);
INSERT INTO countries(id, name, capital, currency, population) values (	126	,'Malawi','Lilongwe','Kwacha',	716400	);
INSERT INTO countries(id, name, capital, currency, population) values (	127	,'Malaysia','Kuala Lumpur','Ringgit',	15355000	);
INSERT INTO countries(id, name, capital, currency, population) values (	128	,'Maldives','Male','Rufiyaa',	86400	);
INSERT INTO countries(id, name, capital, currency, population) values (	129	,'Mali','Bamako','Franc',	249800	);
INSERT INTO countries(id, name, capital, currency, population) values (	130	,'Malta','Valletta','Euro',	240600	);
INSERT INTO countries(id, name, capital, currency, population) values (	131	,'Marshall Islands','Majuro','Dollar',	2200	);
INSERT INTO countries(id, name, capital, currency, population) values (	132	,'Mauritania','Nouakchott','Ouguiya',	75000	);
INSERT INTO countries(id, name, capital, currency, population) values (	133	,'Mauritius','Port Louis','Rupee',	290000	);
INSERT INTO countries(id, name, capital, currency, population) values (	134	,'Mayotte','Mamoudzou','Euro',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	135	,'Mexico','Mexico City','Peso',	31020000	);
INSERT INTO countries(id, name, capital, currency, population) values (	136	,'Micronesia','Palikir','Dollar',	17000	);
INSERT INTO countries(id, name, capital, currency, population) values (	137	,'Moldova','Chisinau','Leu',	1333000	);
INSERT INTO countries(id, name, capital, currency, population) values (	138	,'Monaco','Monaco','Euro',	23000	);
INSERT INTO countries(id, name, capital, currency, population) values (	139	,'Mongolia','Ulan Bator','Tugrik',	330000	);
INSERT INTO countries(id, name, capital, currency, population) values (	140	,'Montenegro','Podgorica','Euro',	280000	);
INSERT INTO countries(id, name, capital, currency, population) values (	141	,'Montserrat','Plymouth','Dollar',	1200	);
INSERT INTO countries(id, name, capital, currency, population) values (	142	,'Morocco','Rabat','Dirham',	13213000	);
INSERT INTO countries(id, name, capital, currency, population) values (	143	,'Mozambique','Maputo','Metical',	613600	);
INSERT INTO countries(id, name, capital, currency, population) values (	144	,'Myanmar','Nay Pyi Taw','Kyat',	110000	);
INSERT INTO countries(id, name, capital, currency, population) values (	145	,'Namibia','Windhoek','Dollar',	127500	);
INSERT INTO countries(id, name, capital, currency, population) values (	146	,'Nauru','Yaren','Dollar',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	147	,'Nepal','Kathmandu','Rupee',	577800	);
INSERT INTO countries(id, name, capital, currency, population) values (	148	,'Netherlands','Amsterdam','Euro',	14872000	);
INSERT INTO countries(id, name, capital, currency, population) values (	149	,'Netherlands Antilles','Willemstad','Guilder',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	150	,'New Caledonia','Noumea','Franc',	85000	);
INSERT INTO countries(id, name, capital, currency, population) values (	151	,'New Zealand','Wellington','Dollar',	3400000	);
INSERT INTO countries(id, name, capital, currency, population) values (	152	,'Nicaragua','Managua','Cordoba',	199800	);
INSERT INTO countries(id, name, capital, currency, population) values (	153	,'Niger','Niamey','Franc',	115900	);
INSERT INTO countries(id, name, capital, currency, population) values (	154	,'Nigeria','Abuja','Naira',	43989000	);
INSERT INTO countries(id, name, capital, currency, population) values (	155	,'Niue','Alofi','Dollar',	1100	);
INSERT INTO countries(id, name, capital, currency, population) values (	156	,'North Korea','Pyongyang','Won',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	157	,'Northern Mariana Islands','Saipan','Dollar',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	158	,'Norway','Oslo','Krone',	4431000	);
INSERT INTO countries(id, name, capital, currency, population) values (	159	,'Oman','Muscat','Rial',	1465000	);
INSERT INTO countries(id, name, capital, currency, population) values (	160	,'Pakistan','Islamabad','Rupee',	20431000	);
INSERT INTO countries(id, name, capital, currency, population) values (	161	,'Palau','Melekeok','Dollar',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	162	,'Palestine','East Jerusalem','Shekel',	1379000	);
INSERT INTO countries(id, name, capital, currency, population) values (	163	,'Panama','Panama City','Balboa',	959800	);
INSERT INTO countries(id, name, capital, currency, population) values (	164	,'Papua New Guinea','Port Moresby','Kina',	125000	);
INSERT INTO countries(id, name, capital, currency, population) values (	165	,'Paraguay','Asuncion','Guarani',	1105000	);
INSERT INTO countries(id, name, capital, currency, population) values (	166	,'Peru','Lima','Sol',	9158000	);
INSERT INTO countries(id, name, capital, currency, population) values (	167	,'Philippines','Manila','Peso',	8278000	);
INSERT INTO countries(id, name, capital, currency, population) values (	168	,'Pitcairn','Adamstown','Dollar',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	169	,'Poland','Warsaw','Zloty',	22452000	);
INSERT INTO countries(id, name, capital, currency, population) values (	170	,'Portugal','Lisbon','Euro',	5168000	);
INSERT INTO countries(id, name, capital, currency, population) values (	171	,'Puerto Rico','San Juan','Dollar',	1000000	);
INSERT INTO countries(id, name, capital, currency, population) values (	172	,'Qatar','Doha','Rial',	563800	);
INSERT INTO countries(id, name, capital, currency, population) values (	173	,'Republic of the Congo','Brazzaville','Franc',	245200	);
INSERT INTO countries(id, name, capital, currency, population) values (	174	,'Reunion','Saint-Denis','Euro',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	175	,'Romania','Bucharest','Leu',	7787000	);
INSERT INTO countries(id, name, capital, currency, population) values (	176	,'Russia','Moscow','Ruble',	40853000	);
INSERT INTO countries(id, name, capital, currency, population) values (	177	,'Rwanda','Kigali','Franc',	450000	);
INSERT INTO countries(id, name, capital, currency, population) values (	178	,'Saint Barthelemy','Gustavia','Euro',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	179	,'Saint Helena','Jamestown','Pound',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	180	,'Saint Kitts and Nevis','Basseterre','Dollar',	17000	);
INSERT INTO countries(id, name, capital, currency, population) values (	181	,'Saint Lucia','Castries','Dollar',	142900	);
INSERT INTO countries(id, name, capital, currency, population) values (	182	,'Saint Martin','Marigot','Euro',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	183	,'Saint Pierre and Miquelon','Saint-Pierre','Euro',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	184	,'Saint Vincent and the Grenadines','Kingstown','Dollar',	76000	);
INSERT INTO countries(id, name, capital, currency, population) values (	185	,'Samoa','Apia','Tala',	9000	);
INSERT INTO countries(id, name, capital, currency, population) values (	186	,'San Marino','San Marino','Euro',	17000	);
INSERT INTO countries(id, name, capital, currency, population) values (	187	,'Sao Tome and Principe','Sao Tome','Dobra',	26700	);
INSERT INTO countries(id, name, capital, currency, population) values (	188	,'Saudi Arabia','Riyadh','Rial',	9774000	);
INSERT INTO countries(id, name, capital, currency, population) values (	189	,'Senegal','Dakar','Franc',	1818000	);
INSERT INTO countries(id, name, capital, currency, population) values (	190	,'Serbia','Belgrade','Dinar',	4107000	);
INSERT INTO countries(id, name, capital, currency, population) values (	191	,'Seychelles','Victoria','Rupee',	32000	);
INSERT INTO countries(id, name, capital, currency, population) values (	192	,'Sierra Leone','Freetown','Leone',	14900	);
INSERT INTO countries(id, name, capital, currency, population) values (	193	,'Singapore','Singapore','Dollar',	3235000	);
INSERT INTO countries(id, name, capital, currency, population) values (	194	,'Sint Maarten','Philipsburg','Guilder',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	195	,'Slovakia','Bratislava','Euro',	4063000	);
INSERT INTO countries(id, name, capital, currency, population) values (	196	,'Slovenia','Ljubljana','Euro',	1298000	);
INSERT INTO countries(id, name, capital, currency, population) values (	197	,'Solomon Islands','Honiara','Dollar',	10000	);
INSERT INTO countries(id, name, capital, currency, population) values (	198	,'Somalia','Mogadishu','Shilling',	106000	);
INSERT INTO countries(id, name, capital, currency, population) values (	199	,'South Africa','Pretoria','Rand',	4420000	);
INSERT INTO countries(id, name, capital, currency, population) values (	200	,'South Korea','Seoul','Won',	39400000	);
INSERT INTO countries(id, name, capital, currency, population) values (	201	,'South Sudan','Juba','Pound',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	202	,'Spain','Madrid','Euro',	28119000	);
INSERT INTO countries(id, name, capital, currency, population) values (	203	,'Sri Lanka','Colombo','Rupee',	1777000	);
INSERT INTO countries(id, name, capital, currency, population) values (	204	,'Sudan','Khartoum','Pound',	4200000	);
INSERT INTO countries(id, name, capital, currency, population) values (	205	,'Suriname','Paramaribo','Dollar',	163000	);
INSERT INTO countries(id, name, capital, currency, population) values (	206	,'Svalbard and Jan Mayen','Longyearbyen','Krone',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	207	,'Swaziland','Mbabane','Lilangeni',	90100	);
INSERT INTO countries(id, name, capital, currency, population) values (	208	,'Sweden','Stockholm','Krona',	8398000	);
INSERT INTO countries(id, name, capital, currency, population) values (	209	,'Switzerland','Berne','Franc',	6152000	);
INSERT INTO countries(id, name, capital, currency, population) values (	210	,'Syria','Damascus','Pound',	4469000	);
INSERT INTO countries(id, name, capital, currency, population) values (	211	,'Taiwan','Taipei','Dollar',	16147000	);
INSERT INTO countries(id, name, capital, currency, population) values (	212	,'Tajikistan','Dushanbe','Somoni',	700000	);
INSERT INTO countries(id, name, capital, currency, population) values (	213	,'Tanzania','Dodoma','Shilling',	678000	);
INSERT INTO countries(id, name, capital, currency, population) values (	214	,'Thailand','Bangkok','Baht',	17483000	);
INSERT INTO countries(id, name, capital, currency, population) values (	215	,'Togo','Lome','Franc',	356300	);
INSERT INTO countries(id, name, capital, currency, population) values (	216	,'Tokelau','','Dollar',	800	);
INSERT INTO countries(id, name, capital, currency, population) values (	217	,'Tonga','Nuku''alofa','Pa''anga',	8400	);
INSERT INTO countries(id, name, capital, currency, population) values (	218	,'Trinidad and Tobago','Port of Spain','Dollar',	593000	);
INSERT INTO countries(id, name, capital, currency, population) values (	219	,'Tunisia','Tunis','Dinar',	3500000	);
INSERT INTO countries(id, name, capital, currency, population) values (	220	,'Turkey','Ankara','Lira',	27233000	);
INSERT INTO countries(id, name, capital, currency, population) values (	221	,'Turkmenistan','Ashgabat','Manat',	80400	);
INSERT INTO countries(id, name, capital, currency, population) values (	222	,'Turks and Caicos Islands','Cockburn Town','Dollar',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	223	,'Tuvalu','Funafuti','Dollar',	4200	);
INSERT INTO countries(id, name, capital, currency, population) values (	224	,'U.S. Virgin Islands','Charlotte Amalie','Dollar',	30000	);
INSERT INTO countries(id, name, capital, currency, population) values (	225	,'Uganda','Kampala','Shilling',	3200000	);
INSERT INTO countries(id, name, capital, currency, population) values (	226	,'Ukraine','Kiev','Hryvnia',	7770000	);
INSERT INTO countries(id, name, capital, currency, population) values (	227	,'United Arab Emirates','Abu Dhabi','Dirham',	3449000	);
INSERT INTO countries(id, name, capital, currency, population) values (	228	,'United Kingdom','London','Pound',	51444000	);
INSERT INTO countries(id, name, capital, currency, population) values (	229	,'United States','Washington','Dollar',	245000000	);
INSERT INTO countries(id, name, capital, currency, population) values (	230	,'Uruguay','Montevideo','Peso',	1405000	);
INSERT INTO countries(id, name, capital, currency, population) values (	231	,'Uzbekistan','Tashkent','Som',	4689000	);
INSERT INTO countries(id, name, capital, currency, population) values (	232	,'Vanuatu','Port Vila','Vatu',	17000	);
INSERT INTO countries(id, name, capital, currency, population) values (	233	,'Vatican','Vatican City','Euro',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	234	,'Venezuela','Caracas','Bolivar',	8918000	);
INSERT INTO countries(id, name, capital, currency, population) values (	235	,'Vietnam','Hanoi','Dong',	23382000	);
INSERT INTO countries(id, name, capital, currency, population) values (	236	,'Wallis and Futuna','Mata Utu','Franc',	1300	);
INSERT INTO countries(id, name, capital, currency, population) values (	237	,'Western Sahara','El-Aaiun','Dirham',	0	);
INSERT INTO countries(id, name, capital, currency, population) values (	238	,'Yemen','Sanaa','Rial',	2349000	);
INSERT INTO countries(id, name, capital, currency, population) values (	239	,'Zambia','Lusaka','Kwacha',	816200	);
INSERT INTO countries(id, name, capital, currency, population) values (	240	,'Zimbabwe','Harare','Dollar',	1423000	);